tasks:
  - before: |
      cd workshop
    init: |
      mvn clean install -DskipTests=true
      clear
      echo 'Ready to test!'
    command: |
      gp open workshop/src/test/java/com/saucedemo/exercises/E2ETests.java

vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - redhat.vscode-xml
